void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int _putchar(char c);
int _sqrt_r2(int a, int b, int c);
int is_prime2(int a, int b);
int strl(char *s);
int is_palind2(char *s, int a, int len);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
int wildcmp2(char *s1, char *s2, int a, int b, int c, int d);
int wildcmp3(char *s1, char *s2, int a, int b, int c, int d);
